// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Korpa {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cart() {
    driver.get("https://bonatti.rs/prijava.html");
    driver.manage().window().setSize(new Dimension(1057, 808));
    driver.findElement(By.cssSelector(".login-form > .form-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector(".login-form > .form-group:nth-child(3) > .form-control")).sendKeys("micamilivojevic0@gmail.com");
    driver.findElement(By.cssSelector(".login-form > .form-group:nth-child(4) > .form-control")).click();
    driver.findElement(By.cssSelector(".login-form > .form-group:nth-child(4) > .form-control")).sendKeys("Focusfocus1*");
    driver.findElement(By.cssSelector(".btn:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .ml-lg-4")).click();
    driver.findElement(By.cssSelector(".submenu > li:nth-child(3) > .search_category_link_bkp")).click();
    driver.findElement(By.cssSelector(".submenu > li:nth-child(3) .fa")).click();
    driver.findElement(By.linkText("Neseseri")).click();
    driver.findElement(By.cssSelector(".col-6:nth-child(2) img")).click();
    driver.findElement(By.cssSelector(".add-to-cart")).click();
    driver.findElement(By.cssSelector(".mr-sm-3")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .ml-lg-4")).click();
    driver.findElement(By.cssSelector("li:nth-child(5) .fa")).click();
    driver.findElement(By.linkText("Helanke")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-6:nth-child(1) img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".col-6:nth-child(3) img")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".add-to-cart"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".py-3")).click();
    driver.findElement(By.cssSelector(".add-to-cart")).click();
    driver.findElement(By.cssSelector(".mr-sm-3")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .ml-lg-4")).click();
    driver.findElement(By.cssSelector("li:nth-child(4) .fa")).click();
    driver.findElement(By.linkText("Majice")).click();
    driver.findElement(By.cssSelector(".col-6:nth-child(1) img")).click();
    driver.findElement(By.cssSelector(".add-to-cart")).click();
    {
      WebElement element = driver.findElement(By.id("addToCartModal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("addToCartModal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("addToCartModal"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".mr-sm-3")).click();
    driver.findElement(By.cssSelector(".fa-shopping-bag")).click();
    assertThat(driver.findElement(By.cssSelector(".cart-sum")).getText(), is("3.338,00"));
  }
}
