// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Registracija {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registracija() {
    driver.get("https://bonatti.rs/registracija.html");
    driver.manage().window().setSize(new Dimension(1054, 808));
    driver.findElement(By.name("first_name")).click();
    driver.findElement(By.name("first_name")).sendKeys("Tijana");
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys("Milivojevic");
    driver.findElement(By.name("address")).click();
    driver.findElement(By.name("address")).sendKeys("Viljusa bb");
    driver.findElement(By.id("select2-place-06-container")).click();
    driver.findElement(By.name("contact_phone")).click();
    driver.findElement(By.name("contact_phone")).sendKeys("0606328810");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("micamilivojevic0@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Focusfocus1*");
    driver.findElement(By.name("repassword")).click();
    driver.findElement(By.name("repassword")).sendKeys("Focusfocus1*");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".recaptcha-checkbox-border")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".form-check:nth-child(15) .fake-checkbox")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(18)")).click();
    assertThat(driver.findElement(By.cssSelector(".register-wrapper > h3")).getText(), is("Poštovani, hvala Vam što ste se registrovali u Bonatti Online prodavnici!\\\\nVaši podaci za dostavu su evidentirani, prilikom kupovine nećete morati opet da ih unosite."));
  }
}
